version: '3.4'

services:
  rpi-influxdb:
    image: arm32v7/influxdb:latest
    restart: always
    networks:
      - weather
    ports:
      - '8083:8083'
      - '8086:8086'
    environment:
      - INFLUXDB_DB=homedb
    volumes:
      - /srv/docker/influxdb:/var/lib/influxdb
  rpi-mosquitto:
    image: rpi-alpine-mosquitto:latest
    restart: always
    networks:
      - weather
    ports:
      - '1883:1883'
  rpi-grafana:
    image: grafana/grafana
    restart: always
    networks:
      - weather
    ports:
      - '3005:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  weather:
