version: '3.4'

services:
  rpi-influxdb:
    image: arm32v7/influxdb:latest
    restart: always
    networks:
      - weather
    ports:
      - '8083:8083'
      - '8086:8086'
    environment:
      - INFLUXDB_DB=homedb
    volumes:
      - /srv/docker/influxdb:/var/lib/influxdb
  rpi-mosquitto:
    image: rpi-alpine-mosquitto:latest
    restart: always
    networks:
      - weather
    ports:
      - '1883:1883'
  rpi-grafana:
    image: grafana/grafana
    restart: always
    networks:
      - weather
    ports:
      - '3005:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana
  weather-app:
    image: weather-app:latest
    restart: always
    networks:
      - weather
    ports:
      - '3004:3000'
      - '9000:9000'
    depends_on:
      - rpi-influxdb
      - rpi-mosquitto
    environment:
      - INFLUXDB_HOST=192.168.1.10
      - MQTT_HOST=192.168.1.10
      - NODEJS_HOST=localhost

volumes:
  grafana-storage:

networks:
  weather:
